bundesland = "Baden-Württemberg"

[hours]
daily_low = 6.0
daily_high = 9.0
weekly_low = 35.0
weekly_high = 40.0

[models.timesheet]
filters = [
    { field = "company_id.name", op = "=", value = "digitalgedacht GmbH" },
]

[models.project]
extra_fields = [
  { name = "product_owner", field = "x_studio_productowner", type = "many2one" },
]
filters = [
    { field = "company_id.name", op = "=", value = "digitalgedacht GmbH" },
]

[models.task]
extra_fields = []
filters = [
    { field = "project_id.name", op = "=", value = "Infrastruktur und Betrieb" },
    { field = "company_id.name", op = "=", value = "digitalgedacht GmbH" },
    { field = "stage_id.name", op = "=", value = "Umsetzung" },
]
